POST localhost:8080/api/rate_forwarder HTTP/1.1
Content-Type: application/json

{
    "forwarder_id": "jRF5k1YB",
    "rating": 5,
    "username": "jacob",
    "key": "baR5ZE7v07z5MygYKlHuWUPJbB0pDDkfmLFNbMuna6lrrwxOH96zQXJojUrUtHq2"
}
